image: maven:3-jdk-11

stages:
  - build
  - test
  - sonar

build:
  stage: build
  script:
    - ./mvnw clean install
    - ./mvnw compiler:compile

test:
  stage: test
  script:
    - ./mvnw test

sonar: 
  stage: sonar
  script:
    mvn package sonar:sonar
    mvn sonar:sonar  "-Dsonar.projectKey=Quizzy"  "-Dsonar.host.url=http://localhost:9000"  "-Dsonar.login=50c0c487c8aa47080768edeb79d16d9562c9bf55"
